name: Build Packer Workflow

on:
  push:
    branches:
      - main

env:
  PRODUCT_VERSION: "1.10.0" 

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_DIALECT: ${{ secrets.DB_DIALECT }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Install PostgreSQL
        run: |
          echo "Installing PostgreSQL"
          sudo apt-get update -y
          sudo apt-get install -y postgresql postgresql-contrib

      - name: Configure PostgreSQL without systemd
        run: |
          echo "Starting PostgreSQL manually"
          sudo service postgresql start

      - name: Update database password
        run: |
          echo "Updating database password"
          sudo -u postgres psql -c "ALTER USER ${{secrets.DB_USER}} WITH PASSWORD '${{secrets.DB_PASSWORD}}';"

      - name: Run tests
        run: npm test 
        
  build-machine-image:
    needs: integration-tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set Packer GitHub API Token
        run: echo "PACKER_GITHUB_API_TOKEN=${{ secrets.PACKER_GITHUB_API_TOKEN }}" >> $GITHUB_ENV

      - name: Create .env file
        run: |
          cat <<EOF > .env
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          aws_region=${{ secrets.AWS_REGION }}
          aws_subnet_id=${{ secrets.AWS_SUBNET_ID }}
          DB_DIALECT=${{ secrets.DB_DIALECT }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          PORT=${{ secrets.PORT }}
          EOF
        shell: bash

      - name: Zip project artifact
        run: zip -r webapp-fork.zip . 
        working-directory: .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'beta,gsutil'

      - name: Save Google Cloud Credentials to File
        run: |
          echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > $HOME/gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-key.json" >> $GITHUB_ENV
        shell: bash

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Run Packer Init
        working-directory: packer
        run: packer init .

      - name: Run Packer Format (Recursive)
        working-directory: packer
        run: packer fmt -recursive .

      - name: Run Packer Validate
        working-directory: packer
        run: packer validate .

      - name: Build Image with Packer (AWS & GCP)
        working-directory: packer
        run: |
          packer build --force \
            -var "aws_region=${{ secrets.AWS_REGION }}" \
            -var "aws_subnet_id=${{ secrets.AWS_SUBNET_ID }}" \
            -var "aws_profile=${{ secrets.AWS_PROFILE }}" \
            -var "ssh_username=${{ secrets.SSH_USERNAME }}" \
            -var "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" \
            -var "DB_NAME=${{ secrets.DB_NAME }}" \
            -var "DB_USER=${{ secrets.DB_USER }}" \
            -var "gcp_project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var "gcp_zone=${{ secrets.GCP_ZONE }}" \
            -var "gcp_source_image_family=${{ secrets.GCP_SOURCE_IMAGE_FAMILY }}" \
            -var "gcp_image_name=${{ secrets.GCP_IMAGE_NAME }}" \
            -var "gcp_image_family=${{ secrets.GCP_IMAGE_FAMILY }}" \
            -var "gcp_machine_type=${{ secrets.GCP_MACHINE_TYPE }}" \
            -var "application_artifact_path=../webapp-fork.zip" \
            .

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Check Manifest Exists
        working-directory: packer
        run: |
          if [ ! -f manifest.json ]; then
            echo "Error: manifest.json not found!"
            exit 1
          fi

      - name: Parse Manifest File
        working-directory: packer
        id: parse-manifest
        run: |
          AWS_AMI_ID=$(jq -r '.builds[] | select(.name == "aws").artifact_id' manifest.json | cut -d':' -f2)
          echo "AWS_AMI_ID=$AWS_AMI_ID" >> $GITHUB_ENV
          GCP_IMAGE_NAME=$(jq -r '.builds[] | select(.name == "gcp").artifact_id | split("/") | last' manifest.json)
          echo "GCP_IMAGE_NAME=$GCP_IMAGE_NAME" >> $GITHUB_ENV

      - name: Validate AWS AMI Availability
        if: env.AWS_AMI_ID != null
        run: |
          echo "Waiting for AMI to become available"
          aws ec2 wait image-available \
            --image-ids ${{ env.AWS_AMI_ID }} \
            --region ${{ secrets.AWS_REGION }}

      - name: Share AWS AMI with DEMO Account
        if: env.AWS_AMI_ID != null
        run: |
          aws ec2 modify-image-attribute \
            --image-id ${{ env.AWS_AMI_ID }} \
            --region ${{ secrets.AWS_REGION }} \
            --launch-permission "Add=[{UserId=${{ secrets.DEMO_AWS_ACCOUNT_ID }}]"}

      - name: Verify GCP Service Account
        if: env.GCP_IMAGE_NAME != null
        run: |
          gcloud iam service-accounts describe ${{ secrets.GCP_DEMO_PROJECT_SA }} \
            --project=${{ secrets.GCP_PROJECT_ID }}