name: PR Validation for Packer Templates

on: 
    pull_request:
        branches: [main]

env:
  PACKER_VERSION: "1.12.0" 

jobs:
    packer-check:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
        
        - name: Install Packer
          uses: hashicorp/setup-packer@main
          with:
            version: ${{ env.PACKER_VERSION }}
        
        - name: Initialize Packer Configuration
          working-directory: packer
          run: packer init .

        - name: Check Packer Formatting
          working-directory: packer
          run: packer fmt -check -recursive .

        - name: validate Packer
          working-directory: packer
          run: packer validate .